### ISSUE TITLE
the subsequence of a certain plankton

### ISSUE THREAD

**Issue by Yangget** [Inria-Chile/awesome-ocean-ai-data#1]
Hello, how to get the subsequence of a certain plankton?

**Comment by luisvalenzuelav** [comment]
Hi, thank you for your question. Firstly, I’d recommend you to view the metadata (excel format) that is associated with the Ocean Microbial Reference Gene Catalog v2 as this will give you an overview of the data available, you can find it [here](https://zenodo.org/record/3539258). The raw data of the Ocean Microbial Reference Gene Catalog v2 that contains metagenomics, metatranscriptomics assays (not single-cell assays), functional annotations, taxonomy and environmental variables can be downloaded from [here](https://www.ebi.ac.uk/biostudies/studies/S-BSST297). 
If you know the id of the plankton metagenome (e.g “Tara_R110002003”) then you can access the data using the oceania-query-data found [here](https://github.com/Inria-Chile/oceania-query-demo) and follow the example in this [notebook](https://github.com/Inria-Chile/oceania-query-demo/blob/main/notebooks/query_tara_r110002003_without_dependency.ipynb) to get the subsequence you are interested in. Furthermore, you can find omics data from plankton communities and single-cell assays in this [repository](https://www.genoscope.cns.fr/tara/).

**Comment by Yangget** [comment]
Thank you very much for your reply !!!

**Comment by Yangget** [comment]
Thank you very much for your reply !!!
